name: expenditures
description: How much did i spend? I actually don't want to know...
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.3
  json_annotation: ^4.8.1
  meta: ^1.7.0
  uuid: ^3.0.6
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
  json_serializable: ^6.3.1
flutter:
  uses-material-design: true
  generate: true
